### ISSUE TITLE
Update user email that previously had no email fails

### ISSUE THREAD

**Issue by Cali93** [supabase/auth-js#737]
# Bug report

- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

If a user signed up with a provider other than email and wants to later on add his email, if the change email confirmation expires it errors out and he can't resend a new confirmation email by calling `updateUser` again. 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Sign up with any provider other than email
2. Call `updateUser({ email: "my-email@gmail.com" })`
3. Change email confirmation expires, user calls `updateUser({ email: "my-email@gmail.com" })` again.
4. Get error `duplicate key value violates unique constraint "identities_pkey"`

## Expected behavior

[This code](https://github.com/supabase/gotrue/blob/9c3ba87d43fb0a7c77caa1d4decfa39b076d5d2c/internal/api/user.go#L170) is checking the email field of the user before creating an identity. But it should really be checking to see if there is an email identity for that user.

## System information

- Version of supabase-js: 2.26.0
- Version of Node.js: 18

**Comment by J0** [comment]
Hey,

Tested this again as a sanity check and it should work with Google OAuth now. Going to close for now but feel free to re-open if there are still issues
