### ISSUE TITLE
`exchangeCodeForSession` throws error instead of returning

### ISSUE THREAD

**Issue by probablykasper** [supabase/auth-js#782]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com).

## Describe the bug

When users log in using PKCE and click the email login link in a different browser, you get this `AuthApiError`:
> invalid request: both auth code and code verifier should be non-empty`

I believe that's expected, but the error is thrown instead of returned from `exchangeCodeForSession()`.

## To Reproduce

1. Set up PKCE with an auth handler like this:
	```ts
	const code = event.url.searchParams.get('code')
	if (typeof code === 'string') {
		const { data, error } = await supabase.auth.exchangeCodeForSession(code).catch((e) => {
			console.log('Thrown error', e);
		});
	}
	```
2. 

## Expected behavior

Since it's a expected and fairly common error, this error should be returned so that it can be properly handled

## System information

- OS: macOS
- Browser: Brave
- Version of supabase-js: 2.33.1
- Version of Node.js: 18.17.1

**Comment by jason-hwang** [comment]
In my opinion, there are two problems:

1. when using `createBrowserClient` in `@supabase/ssr`
2. when using `createClient` from `@supabase/supabase-js` without `auth option`.
 

In both cases 1 and 2, you will not be able to set `auth: { flowType: 'pkce' }` on the supabase client.
This causes problems with the following logic written in GoTrueClient, the actual implementation of Supabase client

![image](https://github.com/supabase/gotrue-js/assets/4724172/23fe1a10-4946-42cb-aa42-a9797d914f6e)

I think this is the reason why `exchangeCodeForSession` returns an error.

**Comment by kafle1** [comment]
Is there any update, I am still getting the same error, everything works fine locally but I get the same error in deployment
am following this doc: https://supabase.com/docs/guides/getting-started/tutorials/with-sveltekit#building-the-app

@probablykasper

**Comment by probablykasper** [comment]
No update afaik. Not really sure what you mean, maybe you misunderstood this issue. Is your error being thrown or returned?

**Comment by kafle1** [comment]
its being thrown

**Comment by therealpurplemana** [comment]
I'm getting this error

**Comment by blakedeckard** [comment]
+1, just realized there is suddenly a 500 on the login redirect

**Comment by AlexisKenAlvarez** [comment]
bump

**Comment by rajaman0** [comment]
same

**Comment by vyas-meet** [comment]
> I was getting this error when accessing my local host from http://localhost:3000 but the generated link was http://192.168.x.x.:3000/. I synced up these variables in my client, server env, native env, and then it all came together.

Thanks man! That helped me :)

**Comment by ylwu** [comment]
I ran into this issue too and realized it's the bug on my end that the original url and redirect url is not with the same domain. Agreeing with others that when this happens the function should return an error instead of throwing

**Comment by syakirurahman** [comment]
i experienced the same issue when login using google oAuth. its only happened locally when i use custom local.host domain (i need to custom it). i already added local.host to config url in supabase auth.

maybe anyone has quick workaround to solve this?

**Comment by Gbillington1** [comment]
+1 I'm facing this too. 

I've tried both server side & client side implementations of `supabase.auth.signInWithOAuth()` listed in [this doc](https://supabase.com/docs/guides/auth/social-login/auth-google?queryGroups=environment&environment=server)

**Comment by GiuseppePapalia** [comment]
> +1, just realized there is suddenly a 500 on the login redirect

Also getting a 500 on login redirect, were you able to resolve this?

**Comment by conner-cross** [comment]
> +1 I'm facing this too. With NextJS and the new `@supabase/ssr` package that uses cookie storage instead of local storage.

> Every time I get to my callback endpoint, I get `AuthApiError: invalid request: both auth code and code verifier should be non-empty` from `supabase.auth.exchangeCodeForSession`.

Seeing this as well with both server side and client side implementations

**Comment by dinhkhanh** [comment]
Facing the same issue, although copy&paste from official documents: https://supabase.com/docs/guides/auth/social-login/auth-google?queryGroups=platform&platform=web&queryGroups=environment&environment=server

**Comment by Gbillington1** [comment]
Is there anything we can do here? This issue basically breaks the entire PKCE flow -- authentication on my application is completely broken now. This is happening with the new supabase SSR package

**Comment by kangmingtay** [comment]
hey everyone, thanks for raising this up, i've put up a PR to fix this since it seems like an issue with how the error is being handled - see #945

**Comment by dinhkhanh** [comment]
After 2 days of hitting the wall, I found out that I mistakenly put middleware.ts file in the root project directory while using Next.js with src folder. Move middleware.ts into src folder, same level with app folder, and everything works fine.

**Comment by mnttnm** [comment]
Hey @kangmingtay 

I am still facing this issue on auth-js 2.65.0

```route error AuthApiError: invalid request: both auth code and code verifier should be non-empty
    at handleError (webpack-internal:///(rsc)/./node_modules/@supabase/auth-js/dist/module/lib/fetch.js:80:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _handleRequest (webpack-internal:///(rsc)/./node_modules/@supabase/auth-js/dist/module/lib/fetch.js:123:9)
    at async _request (webpack-internal:///(rsc)/./node_modules/@supabase/auth-js/dist/module/lib/fetch.js:105:18)
    at async SupabaseAuthClient._exchangeCodeForSession (webpack-internal:///(rsc)/./node_modules/@supabase/auth-js/dist/module/GoTrueClient.js:417:37)
    at async eval (webpack-internal:///(rsc)/./node_modules/@supabase/auth-js/dist/module/GoTrueClient.js:735:28) {
  __isAuthError: true,```
  
  
 I am running Google Auth on local instance.

**Comment by denizkenan** [comment]
Issue is still there. Official documentation for SvelteKit. is broken.

**Comment by denizkenan** [comment]
this line:

https://github.com/supabase/auth-js/blob/8a1ec0602792191bd235d51fd45c0ec2cabdf216/src/GoTrueClient.ts#L590

returns 404 despite the fact that auth.flow_state has the record.

**Comment by theodufort** [comment]
> Hey @kangmingtay
> 
> I am still facing this issue on auth-js 2.65.0
> 
> ```
>     at handleError (webpack-internal:///(rsc)/./node_modules/@supabase/auth-js/dist/module/lib/fetch.js:80:11)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async _handleRequest (webpack-internal:///(rsc)/./node_modules/@supabase/auth-js/dist/module/lib/fetch.js:123:9)
>     at async _request (webpack-internal:///(rsc)/./node_modules/@supabase/auth-js/dist/module/lib/fetch.js:105:18)
>     at async SupabaseAuthClient._exchangeCodeForSession (webpack-internal:///(rsc)/./node_modules/@supabase/auth-js/dist/module/GoTrueClient.js:417:37)
>     at async eval (webpack-internal:///(rsc)/./node_modules/@supabase/auth-js/dist/module/GoTrueClient.js:735:28) {
>   __isAuthError: true,```
>   
>   
>  I am running Google Auth on local instance.
> ```

same
