### ISSUE TITLE
"User with this email not found" error when using generateLink

### ISSUE THREAD

**Issue by jide** [supabase/auth-js#875]
# Bug report

- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

In local development, everything works fine:
```js
  const { data, error } = await supabaseService.auth.admin.generateLink({
    type: "signup",
    email,
    password,
  });
```
Works as expected.

In production, it throws "User with this email not found". I triple checked, email and password are legit non-existing values.

## To Reproduce

I'm unable to reproduce this as local dev works as expected :(

## Expected behavior

I really do not see how this error can be thrown by the generateLink() function.

## System information

- OS: local dev : macOS
- Version of supabase-js: 2.39.7
- Version of Node.js: 20

**Comment by jide** [comment]
Ok, I reproduced this, and I confirm this is a bug recently introduced.

It basically breaks signups for apps where an email is sent using generateLink(), which is really bad.

To reproduce:
- Create a supabase project
- Clone this repository
- Set env vars
- Launch `node index.js`
- It throws `AuthApiError: User with this email not found`

https://github.com/jide/supabase-issue-875

**Comment by jide** [comment]
The issue has been fixed.

<img width="876" alt="Capture d’écran 2024-04-04 à 00 37 52" src="https://github.com/supabase/auth-js/assets/333073/6e0d5602-24e2-4e78-be60-d2f2b5927a4e">

**Comment by ham-evans** [comment]
I'm also experiencing this issue.  Any solutions? Do I need to update my Supabase Postgres version?

**Comment by jide** [comment]
Reopening to bring supabase maintainers attention.

**Comment by vacas5** [comment]
Currently experiencing something similar, but using "invite" type when generating a link.

For local development, all is well, but in github actions the following is failing with `[AuthApiError]: User with this email not found`

```
const { data, error } = await supabase.auth.admin.generateLink({
  type: 'invite',
  email
})
```

System information:

@supabase/supabase-js 2.39.3

node-version: 18.19.1

Operating System
  Ubuntu
  22.04.4
  LTS

**Comment by erdemdev** [comment]
Possible workaround for now:

```ts
import { supabase } from "./lib";

async function init() {
  const createUserResult = await supabase.auth.admin.createUser({
    email: "test@mail.com",
    password: "123456789.",
  });
  console.log("🚀 ~ test ~ createUserResult:", createUserResult);

  const generateLinkResult = await supabase.auth.admin.generateLink({
    email: "test@mail.com",
    type: "signup",
    password: "123456789.",
  });
  console.log("🚀 ~ test ~ generateLinkResult:", generateLinkResult);

  const verifyOtpResult = await supabase.auth.verifyOtp({
    email: "test@mail.com",
    type: "email",
    token: generateLinkResult.data.properties?.email_otp ?? "",
  });
  console.log("🚀 ~ test ~ verifyOtpResult:", verifyOtpResult);

  await supabase.auth.admin.deleteUser(verifyOtpResult.data.user?.id ?? "");
}

init();
```

**Comment by nienkedekker** [comment]
Yep, same here. I'm on the following packages:
```
@supabase/ssr: 0.3.0,
supabase/supabase-js: 2.42.5,
supabase: 1.163.2
```
My machine:
Node version 18.19.0
MacOS 14.4.1 (23E224)

The error:
```
{
 __isAuthError: true,
status: 404,
code: 'user_not_found'
 }
```

The code triggering the error:
```
   const { data: linkData, error: linkError } =
      await supabase.auth.admin.generateLink({
        type: "signup",
        email,
        password,
      });
```

**Comment by tech-betastreets** [comment]
Facing same issue.

```javascript
  const link = await supabase.auth.admin.generateLink({
    type: 'signup',
    email,
    password
  });
```

Is giving the following error

`error: AuthApiError: User with this email not found`

App
@supabase/supabase-js:  2.42.7
NodeJs: v18.18.0

Supabase
GoTrue version: 2.148.0
PostgREST version: 12.0.2
Postgres version: 15.1.1.41

**Comment by vacas5** [comment]
For my issue, the reason that it was working for local development but not in Github actions is because locally we were using v1.153.4 of supabase cli, which was installing v2.130.0 of gotrue. When I set my action to the following the issue resolved.

```
- name: Setup Supabase
        uses: supabase/setup-cli@v1
        with:
          version: 1.153.4
```

I have yet to try upgrading to the latest version of the CLI.

**Comment by kangmingtay** [comment]
@vacas5 upgrading the CLI upgrades the auth service's docker image version used which should contain the fix
