### ISSUE TITLE
supabase-js@2.42.5 breaks client auth with edge functions

### ISSUE THREAD

**Issue by b-snel** [supabase/auth-js#881]
# Bug report

- [ ] I confirm this is a bug with Supabase, not with my own application. 
- [ ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When I get the authorization header from the client in an edge function I'm unable to make a supabase client with the newest version of supabase-js (using deno edge functions). The behavior doesn't happen on 2.42.4 and below. I have rolled back but I wanted to bring this to your attention.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

## Expected behavior

Able to get user auth details. See code snippet at bottom of how I typically do that.

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

## Additional context

`import { corsHeaders } from '../_shared/cors.ts'
import { createClient } from "supabase-js"
import { createSupabaseClient } from '../_shared/supabaseClient.ts'

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  const authHeader = req.headers.get('Authorization')!
  const supabaseClient = createSupabaseClient(authHeader)

  // Get the session or user object
  const { data } = await supabaseClient.auth.getUser()
  const user = data.user

  if (!user) {
    throw new Error('User is null');
  }

}`

and here is the definition for my client function:
`import { createClient, SupabaseClient } from "supabase-js"

export function createSupabaseClient(authHeader: string): SupabaseClient {
  return createClient(
    Deno.env.get('SUPABASE_URL') ?? '',
    Deno.env.get('SUPABASE_ANON_KEY') ?? '',
    { global: { headers: { Authorization: authHeader } } }
  );
}`

**Comment by zguo123** [comment]
> @kangmingtay Does the supabase-js team know about this fix? Users are still running into the issue on Edge functions and your fix here has not been merged with supabase-js yet, or released.

You can use any version below 2.42.4

**Comment by GaryAustin1** [comment]
Sure and that's what I'm telling user that come to discord, or github and I see them.  Or just use getUser(jwt) with the jwt from the header.
BUT users are hitting this and not knowing what the issue is, so wasting alot of time on their part till they find the solution.

**Comment by jareddr** [comment]
Just to reinforce what GaryAustin1 is saying...  

When I wrote in to support with this issue I got back:
```
Thank you for contacting Supabase support. This works and I have it in a few of my edge functions.

Have you tried logging the headers to debug it?
```

In reference to calling `auth.getUser()` with no JWT.    It seems like the organization doesn't understand the existence or magnitude of the problem.

It's a big breaking issue for anyone who copied code form the JavaScript edge function auth docs.  It's insidious in that it only shows up when you deploy a new version of your edge function and only if you are using the import line from the docs which just references `@supabase/supabase-js@2`.  

Then you spend a lot of time trying to figure out how you completely broke your edge function with whatever change you made.

**Comment by andreicos1** [comment]
what if we want to use other auth functions like updateUser? Is this just not possible?

**Comment by j4w8n** [comment]
> what if we want to use other auth functions like updateUser? Is this just not possible?

@andreicos1, you have two possibilities for that when in an edge function:

1. If using an anon client: call `supabase.auth.setSession({ access_token, refresh_token })` first. Both are required, but depending on your use-case, you could just pass a dummy string as the refresh token. Be sure that the supabase client has `autoRefreshToken` set to `false`.
2. If using a service client: call `supabase.auth.admin.updateUserById()` - which you'd need their user id of course.
