### ISSUE TITLE
New error code is missing in error object

### ISSUE THREAD

**Issue by melchiorb** [supabase/auth-js#884]
# Bug report

- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

The new error code (which is correctly sent by the server) is not accessible in auth-js.

Example when using non existend email address on signin:

Server response:
`{"code":"otp_disabled","message":"Signups not allowed for otp"}`

The error object returned by "supabase.auth.signInWithOtp":
`error.code = undefined`
`error.message = "Signups not allowed for otp"`

## Expected behavior

`error.code = "otp_disabled"`

## System information

- Version of auth-js: 2.63.1

**Comment by J0** [comment]
Hey thanks for flagging,

Going to close this as the code should show up now

<img width="532" alt="image" src="https://github.com/user-attachments/assets/a9cce8f2-5822-4959-a81a-77ad199ef5e6">


Feel free to re-open if that's not the case.
