### ISSUE TITLE
Send Supabase emails with supabase adress using resend.

### ISSUE THREAD

**Issue by enzzzooo** [supabase/auth-js#968]
Hello All,

I am looking to send an email using resend with the default ****.supabase.co email but I am unable to verify the email DNS records as resend requires as found at https://resend.com/domains/ then clicking on one of the domains

**Comment by j4w8n** [comment]
I believe you have to use one of your own domains @enzzzooo

**Comment by enzzzooo** [comment]
> I believe you have to use one of your own domains @enzzzooo

Yes you're right, though this is kind of an issue as I cannot find any domain that is free. Kind of why I started to use Supabase.

**Comment by j4w8n** [comment]
Yeah, you're not gonna find that. You can register a domain with Cloudflare pretty cheap.

**Comment by enzzzooo** [comment]
> Yeah, you're not gonna find that. You can register a domain with Cloudflare pretty cheap.

Yeah, since I do get a vercel domain for free do you belive there is a way to use that for sending emails? Or something like netlify or another free option?

**Comment by j4w8n** [comment]
> > Yeah, you're not gonna find that. You can register a domain with Cloudflare pretty cheap.
> 
> Yeah, since I do get a vercel domain for free do you belive there is a way to use that for sending emails? Or something like netlify or another free option?

> I'm not sure
